import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { OrderProvider } from "@/context/Order";


export const metadata = {
  title: "Furninest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <OrderProvider>
          <body>
            {children}
          </body>
        </OrderProvider>
      </AuthProvider>
    </html>
  );
}
